// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlcMPdCC4_O8yI1SA-3-HXnC8Lp_zzqp0',
    appId: '1:464997885481:web:0aaeae645067a780ad9e38',
    messagingSenderId: '464997885481',
    projectId: 'news-app-c042a',
    authDomain: 'news-app-c042a.firebaseapp.com',
    storageBucket: 'news-app-c042a.appspot.com',
    measurementId: 'G-MQNHXWJXD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaBuU_-Oybp4ATvjBk_LDrMkWb9ClwylU',
    appId: '1:464997885481:android:eba388cd08575ac8ad9e38',
    messagingSenderId: '464997885481',
    projectId: 'news-app-c042a',
    storageBucket: 'news-app-c042a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYqIn5744L8WWYazSpQkG2pqeSUwrsvA',
    appId: '1:464997885481:ios:0fc7ed787b714f99ad9e38',
    messagingSenderId: '464997885481',
    projectId: 'news-app-c042a',
    storageBucket: 'news-app-c042a.appspot.com',
    iosBundleId: 'com.example.flutternews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyYqIn5744L8WWYazSpQkG2pqeSUwrsvA',
    appId: '1:464997885481:ios:0fc7ed787b714f99ad9e38',
    messagingSenderId: '464997885481',
    projectId: 'news-app-c042a',
    storageBucket: 'news-app-c042a.appspot.com',
    iosBundleId: 'com.example.flutternews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlcMPdCC4_O8yI1SA-3-HXnC8Lp_zzqp0',
    appId: '1:464997885481:web:47a887129dcf3a10ad9e38',
    messagingSenderId: '464997885481',
    projectId: 'news-app-c042a',
    authDomain: 'news-app-c042a.firebaseapp.com',
    storageBucket: 'news-app-c042a.appspot.com',
    measurementId: 'G-D4H876RKMJ',
  );
}
